// <auto-generated />
namespace To_Do_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dodanie_tabeli_WorkTasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodanie_tabeli_WorkTasks));
        
        string IMigrationMetadata.Id
        {
            get { return "202405091607369_dodanie_tabeli_WorkTasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
